# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daab09f19a7349a80e35060e28b946e79fe22edf3b4939d83bde6b18a8fadfeb0eb7989dfa0cc6107295b9e154b4cb58dbc656329a56a066a307cce03f786ff8

test:
  secret_key_base: 2083178114ac10a233d191f320d9c9f54f9b776c5e4d279e3382954335b2902d3667f2ab1988a70dc6433c2e2b2ab297b6576f476d56d1c3e8ce028204329576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
